/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Fan } from '../../models/fan';

export interface ApiFanGet$Plain$Params {
}

export function apiFanGet$Plain(http: HttpClient, rootUrl: string, params?: ApiFanGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Fan>>> {
  const rb = new RequestBuilder(rootUrl, apiFanGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Fan>>;
    })
  );
}

apiFanGet$Plain.PATH = '/api/Fan';
