/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Fan } from '../../models/fan';

export interface ApiFanIdGet$Json$Params {
  id: number;
}

export function apiFanIdGet$Json(http: HttpClient, rootUrl: string, params: ApiFanIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Fan>> {
  const rb = new RequestBuilder(rootUrl, apiFanIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Fan>;
    })
  );
}

apiFanIdGet$Json.PATH = '/api/Fan/{id}';
