/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Fan } from '../../models/fan';

export interface ApiFanIdGet$Plain$Params {
  id: number;
}

export function apiFanIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiFanIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Fan>> {
  const rb = new RequestBuilder(rootUrl, apiFanIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Fan>;
    })
  );
}

apiFanIdGet$Plain.PATH = '/api/Fan/{id}';
