/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CarInput } from './models/car-input';
export type { CategoryDto } from './models/category-dto';
export type { CreateOrderDetailDto } from './models/create-order-detail-dto';
export type { CreateOrderDto } from './models/create-order-dto';
export type { CreateProductDto } from './models/create-product-dto';
export type { LoginDto } from './models/login-dto';
export type { OrderDetailDto } from './models/order-detail-dto';
export type { OrderDto } from './models/order-dto';
export type { ProblemDetails } from './models/problem-details';
export type { ProductDto } from './models/product-dto';
export type { TokenResponse } from './models/token-response';
export type { UpdateProductDto } from './models/update-product-dto';
