/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { CreateProductDto } from './models/create-product-dto';
export type { ProblemDetails } from './models/problem-details';
export type { ProductDto } from './models/product-dto';
export type { UpdateProductDto } from './models/update-product-dto';
