/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarInput {
  color?: string | null;
  features?: Array<string> | null;
  make?: string | null;
  mileage?: number;
  model?: string | null;
  price?: number;
  vin?: string | null;
  year?: number;
}
