/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateOrderDetailDto } from '../models/create-order-detail-dto';
export interface CreateOrderDto {
  customerName: string;
  orderDate: string;
  orderDetails?: Array<CreateOrderDetailDto> | null;
}
