/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDetailDto } from '../models/order-detail-dto';
export interface OrderDto {
  customerName: string;
  orderDate: string;
  orderDetails?: Array<OrderDetailDto> | null;
  orderId?: number;
  totalAmount?: number;
}
