/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductDto } from '../models/product-dto';
export interface OrderDetailDto {
  amount?: number;
  orderDetailId?: number;
  orderId?: number;
  product?: ProductDto;
  productId: number;
  quantity: number;
  unitPrice?: number;
}
