/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryDto } from '../models/category-dto';
export interface ProductDto {
  category?: CategoryDto;
  id?: number;
  name?: string | null;
  price?: number;
  stock?: number;
}
