/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCarsGet } from '../fn/cars/api-cars-get';
import { ApiCarsGet$Params } from '../fn/cars/api-cars-get';
import { apiCarsPost } from '../fn/cars/api-cars-post';
import { ApiCarsPost$Params } from '../fn/cars/api-cars-post';

@Injectable({ providedIn: 'root' })
export class CarsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCarsGet()` */
  static readonly ApiCarsGetPath = '/api/Cars';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCarsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCarsGet$Response(params?: ApiCarsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCarsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCarsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCarsGet(params?: ApiCarsGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCarsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCarsPost()` */
  static readonly ApiCarsPostPath = '/api/Cars';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCarsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCarsPost$Response(params?: ApiCarsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCarsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCarsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCarsPost(params?: ApiCarsPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCarsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
