/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiKafkaConsumerConsumeGet } from '../fn/kafka-consumer/api-kafka-consumer-consume-get';
import { ApiKafkaConsumerConsumeGet$Params } from '../fn/kafka-consumer/api-kafka-consumer-consume-get';

@Injectable({ providedIn: 'root' })
export class KafkaConsumerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiKafkaConsumerConsumeGet()` */
  static readonly ApiKafkaConsumerConsumeGetPath = '/api/KafkaConsumer/consume';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiKafkaConsumerConsumeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiKafkaConsumerConsumeGet$Response(params?: ApiKafkaConsumerConsumeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiKafkaConsumerConsumeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiKafkaConsumerConsumeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiKafkaConsumerConsumeGet(params?: ApiKafkaConsumerConsumeGet$Params, context?: HttpContext): Observable<void> {
    return this.apiKafkaConsumerConsumeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
